spring:
  datasource:
    platform: mysql
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
  messages:
    basename: messages/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: false
server:
  context-path: /commutify

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/commutify?useSSL=false
    username: dbuser
    password: dbp4ss
    initialize: true
  thymeleaf:
    cache: false
security:
  strength: 10

---

spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DB_PORT_3306_TCP_ADDR}:${DB_PORT_3306_TCP_PORT}/${DB_ENV_MYSQL_DATABASE}
    username: ${DB_ENV_MYSQL_USER}
    password: ${DB_ENV_MYSQL_PASSWORD}
    initialize: true
  thymeleaf:
    cache: true
security:
  strength: 10

---

spring:
  profiles: koding
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/commutify?useSSL=false
    username: dbuser
    password: dbpass
    initialize: false
  thymeleaf:
    cache: true
security:
  strength: 10